### ISSUE TITLE
[bug] Not enough log output for Delta task error

### ISSUE THREAD

**Issue by lencyforce** [delta-mpc/delta-node#19]
**Describe the bug**
Not enough log output for Delta task error

**Expected behavior**
There should be explanations about what goes wrong here

**Screenshots**
![d9780d05059416cc02a7b9c6cc885a7](https://user-images.githubusercontent.com/3778069/158290935-4a6f6ef7-5ca7-474d-bc45-2ae73db3abff.png)

**Comment by mh739025250** [comment]
fixed in pr #27
